In [1]:
import joblib
import pandas as pd
import numpy as np

In [2]:
stable_model = joblib.load("../model/stable/XGBC_model.joblib")

insulator_model = joblib.load("../model/insulator/XGBC_model.joblib")

bandgap_model = joblib.load("../model/bandgap/XGBR_model.joblib")

In [3]:
df = pd.read_csv("../data/processed/synthetic_compounds.csv")

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15882608 entries, 0 to 15882607
Data columns (total 62 columns):
 #   Column   Dtype
---  ------   -----
 0   A1       object
 1   A1_OS    int64
 2   B1       object
 3   B1_OS    int64
 4   A2       object
 5   A2_OS    int64
 6   B2       object
 7   B2_OS    int64
 8   Formula  object
 9   Type     object
 10  X-A1     float64
 11  X-A2     float64
 12  X-B1     float64
 13  X-B2     float64
 14  I-A1     float64
 15  I-A2     float64
 16  I-B1     float64
 17  I-B2     float64
 18  P-A1     float64
 19  P-A2     float64
 20  P-B1     float64
 21  P-B2     float64
 22  R-A1     float64
 23  R-A2     float64
 24  R-B1     float64
 25  R-B2     float64
 26  RA-A1    float64
 27  RA-A2    float64
 28  RA-B1    float64
 29  RA-B2    float64
 30  H-A1     float64
 31  H-A2     float64
 32  H-B1     float64
 33  H-B2     float64
 34  L-A1     float64
 35  L-A2     float64
 36  L-B1     float64
 37  L-B2     float64
 38  EA-A1    float64
 39  EA-A2    float64
 40  EA-B1    float64
 41  EA-B2    float64
 42  TC-A1    float64
 43  TC-A2    float64
 44  TC-B1    float64
 45  TC-B2    float64
 46  TE-A1    float64
 47  TE-A2    float64
 48  TE-B1    float64
 49  TE-B2    float64
 50  EH-A1    float64
 51  EH-A2    float64
 52  EH-B1    float64
 53  EH-B2    float64
 54  BE-A1    int64
 55  BE-A2    int64
 56  BE-B1    int64
 57  BE-B2    int64
 58  3DOE-A1  float64
 59  3DOE-A2  float64
 60  3DOE-B1  float64
 61  3DOE-B2  float64
dtypes: float64(48), int64(8), object(6)
memory usage: 7.3+ GB

In [5]:
df.columns

Index(['A1', 'A1_OS', 'B1', 'B1_OS', 'A2', 'A2_OS', 'B2', 'B2_OS', 'Formula',
       'Type', 'X-A1', 'X-A2', 'X-B1', 'X-B2', 'I-A1', 'I-A2', 'I-B1', 'I-B2',
       'P-A1', 'P-A2', 'P-B1', 'P-B2', 'R-A1', 'R-A2', 'R-B1', 'R-B2', 'RA-A1',
       'RA-A2', 'RA-B1', 'RA-B2', 'H-A1', 'H-A2', 'H-B1', 'H-B2', 'L-A1',
       'L-A2', 'L-B1', 'L-B2', 'EA-A1', 'EA-A2', 'EA-B1', 'EA-B2', 'TC-A1',
       'TC-A2', 'TC-B1', 'TC-B2', 'TE-A1', 'TE-A2', 'TE-B1', 'TE-B2', 'EH-A1',
       'EH-A2', 'EH-B1', 'EH-B2', 'BE-A1', 'BE-A2', 'BE-B1', 'BE-B2',
       '3DOE-A1', '3DOE-A2', '3DOE-B1', '3DOE-B2'],
      dtype='object')

In [6]:
df = df.rename(columns={'Type': 'type'})

In [ ]:
from sklearn.preprocessing import  OneHotEncoder

onehot_encoder = OneHotEncoder(sparse_output=False)
type_encoded = onehot_encoder.fit_transform(df[['type']])
type_encoded_df = pd.DataFrame(type_encoded, columns=onehot_encoder.get_feature_names_out(['type']))

df_prep = pd.concat([df, type_encoded_df], axis=1)

df_prep = df.drop(columns=['type','A1', 'A2', 'B1', 'B2','Formula'])

display(df_prep.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15882608 entries, 0 to 15882607
Data columns (total 60 columns):
 #   Column           Dtype
---  ------           -----
 0   A1_OS            int64
 1   B1_OS            int64
 2   A2_OS            int64
 3   B2_OS            int64
 4   X-A1             float64
 5   X-A2             float64
 6   X-B1             float64
 7   X-B2             float64
 8   I-A1             float64
 9   I-A2             float64
 10  I-B1             float64
 11  I-B2             float64
 12  P-A1             float64
 13  P-A2             float64
 14  P-B1             float64
 15  P-B2             float64
 16  R-A1             float64
 17  R-A2             float64
 18  R-B1             float64
 19  R-B2             float64
 20  RA-A1            float64
 21  RA-A2            float64
 22  RA-B1            float64
 23  RA-B2            float64
 24  H-A1             float64
 25  H-A2             float64
 26  H-B1             float64
 27  H-B2             float64
 28  L-A1             float64
 29  L-A2             float64
 30  L-B1             float64
 31  L-B2             float64
 32  EA-A1            float64
 33  EA-A2            float64
 34  EA-B1            float64
 35  EA-B2            float64
 36  TC-A1            float64
 37  TC-A2            float64
 38  TC-B1            float64
 39  TC-B2            float64
 40  TE-A1            float64
 41  TE-A2            float64
 42  TE-B1            float64
 43  TE-B2            float64
 44  EH-A1            float64
 45  EH-A2            float64
 46  EH-B1            float64
 47  EH-B2            float64
 48  BE-A1            int64
 49  BE-A2            int64
 50  BE-B1            int64
 51  BE-B2            int64
 52  3DOE-A1          float64
 53  3DOE-A2          float64
 54  3DOE-B1          float64
 55  3DOE-B2          float64
 56  type_A1A2B1B2O6  float64
 57  type_A1A2B2O6    float64
 58  type_A2B1B2O6    float64
 59  type_ABO3        float64
dtypes: float64(52), int64(8)
memory usage: 7.1 GB

None

In [8]:
cols_for_bandgap = ['A1_OS', 'A2_OS', 'B1_OS', 'B2_OS', 'Insulator',
       'stable', 'X-A1', 'X-A2', 'X-B1', 'X-B2', 'I-A1', 'I-A2', 'I-B1',
       'I-B2', 'P-A1', 'P-A2', 'P-B1', 'P-B2', 'R-A1', 'R-A2', 'R-B1', 'R-B2',
       'RA-A1', 'RA-A2', 'RA-B1', 'RA-B2', 'H-A1', 'H-A2', 'H-B1', 'H-B2',
       'L-A1', 'L-A2', 'L-B1', 'L-B2', 'EA-A1', 'EA-A2', 'EA-B1', 'EA-B2',
       'TC-A1', 'TC-A2', 'TC-B1', 'TC-B2', 'TE-A1', 'TE-A2', 'TE-B1', 'TE-B2',
       'EH-A1', 'EH-A2', 'EH-B1', 'EH-B2', 'BE-A1', 'BE-A2', 'BE-B1', 'BE-B2',
       '3DOE-A1', '3DOE-A2', '3DOE-B1', '3DOE-B2', 'type_A1A2B1B2O6',
       'type_A1A2B2O6', 'type_A2B1B2O6', 'type_ABO3']
cols_for_insulator = ['A1_OS', 'A2_OS', 'B1_OS', 'B2_OS', 'stable', 'X-A1', 'X-A2', 
       'X-B1', 'X-B2', 'I-A1','I-A2', 'I-B1', 'I-B2', 'P-A1', 'P-A2', 'P-B1', 'P-B2', 
       'R-A1', 'R-A2', 'R-B1','R-B2', 'RA-A1', 'RA-A2', 'RA-B1', 'RA-B2', 'H-A1', 
       'H-A2', 'H-B1', 'H-B2', 'L-A1','L-A2', 'L-B1', 'L-B2', 'EA-A1', 'EA-A2', 
       'EA-B2', 'TC-A1', 'TC-A2', 'TC-B1','TC-B2', 'TE-A1', 'TE-A2', 'TE-B1', 
       'TE-B2', 'EH-A1', 'EH-B1', 'EH-B2', 'BE-A1', 'BE-A2', 'BE-B1', 'BE-B2', 
       '3DOE-A1', '3DOE-A2', '3DOE-B1', 'type_A1A2B1B2O6','type_A1A2B2O6', 'type_A2B1B2O6', 'type_ABO3']

cols_for_stable = ['A1_OS', 'A2_OS', 'B1_OS', 'B2_OS', 'X-A1',
       'X-A2', 'X-B1','X-B2', 'I-A1', 'I-A2', 'I-B1', 'I-B2', 'P-A1', 'P-A2', 'P-B1', 
       'P-B2', 'R-A1','R-A2', 'R-B1', 'R-B2', 'RA-A1', 'RA-A2', 'RA-B1', 'RA-B2', 
       'H-A1', 'H-A2', 'H-B1', 'H-B2', 'L-A1', 'L-A2', 'L-B1', 'L-B2', 'EA-A1', 
       'EA-A2', 'EA-B1','EA-B2', 'TC-A1', 'TC-A2', 'TC-B1', 'TC-B2', 'TE-A1', 'TE-A2',
       'TE-B1','TE-B2', 'EH-A1', 'EH-A2', 'EH-B1', 'EH-B2', 'BE-A1', 'BE-A2', 'BE-B1', 
       'BE-B2', '3DOE-A1', '3DOE-A2', '3DOE-B1', '3DOE-B2', 'type_A1A2B1B2O6', 
       'type_A1A2B2O6', 'type_A2B1B2O6', 'type_ABO3']

In [9]:
col_to_drop_for_stable = ['X-B2', 'A1_OS', 'P-B2', 'BE-B2','EA-A1','RA-B1', 'EA-A2']

In [10]:
for col in col_to_drop_for_stable:
    if col in cols_for_stable:
        cols_for_stable.remove(col)
print(cols_for_stable)

['A2_OS', 'B1_OS', 'B2_OS', 'X-A1', 'X-A2', 'X-B1', 'I-A1', 'I-A2', 'I-B1', 'I-B2', 'P-A1', 'P-A2', 'P-B1', 'R-A1', 'R-A2', 'R-B1', 'R-B2', 'RA-A1', 'RA-A2', 'RA-B2', 'H-A1', 'H-A2', 'H-B1', 'H-B2', 'L-A1', 'L-A2', 'L-B1', 'L-B2', 'EA-B1', 'EA-B2', 'TC-A1', 'TC-A2', 'TC-B1', 'TC-B2', 'TE-A1', 'TE-A2', 'TE-B1', 'TE-B2', 'EH-A1', 'EH-A2', 'EH-B1', 'EH-B2', 'BE-A1', 'BE-A2', 'BE-B1', '3DOE-A1', '3DOE-A2', '3DOE-B1', '3DOE-B2', 'type_A1A2B1B2O6', 'type_A1A2B2O6', 'type_A2B1B2O6', 'type_ABO3']

In [16]:
temp_df = df_prep[cols_for_stable]
df_prep['stable'] = stable_model.predict(temp_df)
temp_df = df_prep[cols_for_insulator]
df_prep['Insulator'] = insulator_model.predict(temp_df)
temp_df = df_prep[cols_for_bandgap]
df_prep['PBE_bandgap'] = bandgap_model.predict(temp_df)

In [17]:
df['stable'] = df_prep['stable']
df['Insulator'] = df_prep['Insulator']
df['PBE_bandgap'] = df_prep['PBE_bandgap']

In [18]:
df.head()

,A1,A1_OS,B1,B1_OS,A2,A2_OS,B2,B2_OS,Formula,type,...,3DOE-A2,3DOE-B1,3DOE-B2,type_A1A2B1B2O6,type_A1A2B2O6,type_A2B1B2O6,type_ABO3,stable,Insulator,PBE_bandgap
0,Pm,2,Mn,2,Pm,2,Mn,6,PmMnO3,ABO3,...,-37.625433,-0.26654,-0.266540,0.0,0.0,0.0,1.0,1,0,0.041108
1,Pm,2,Mn,3,Pm,2,Bi,5,PmMnBiO6,A2B1B2O6,...,-37.625433,-0.26654,-95.532476,0.0,0.0,1.0,0.0,1,0,0.040267
2,Pm,2,Mn,6,Pm,2,Co,2,PmMnCoO6,A2B1B2O6,...,-37.625433,-0.26654,-0.322368,0.0,0.0,1.0,0.0,1,0,0.027343
3,Pm,2,Mn,3,Pm,3,Ir,4,PmMnIrO6,A2B1B2O6,...,-37.625433,-0.26654,-75.485027,0.0,0.0,1.0,0.0,1,0,0.022368
4,Pm,2,Mn,7,Pm,2,Tl,1,PmMnTlO6,A2B1B2O6,...,-37.625433,-0.26654,-88.328299,0.0,0.0,1.0,0.0,1,0,0.063391

In [19]:
df.drop(columns=['type_A1A2B1B2O6', 'type_A1A2B2O6', 'type_A2B1B2O6', 'type_ABO3'], inplace=True)

In [20]:
df.to_csv("../data/processed/predicted_synthetic_compounds.csv", index=False)

In [ ]:
df['Tolerance_Factor'] = (df['R-A(pm)'] + df['R-X(pm)']) / (np.sqrt(2) * ((df['R-B1(pm)'] + df['R-B3(pm)']) / 2 + df['R-X(pm)']))
df['Octahedral_Factor'] = (df['R-B1(pm)'] + df['R-B3(pm)']) / (2 * df['R-X(pm)'])

KeyError: 'R-A(pm)'

In [ ]:
filter_df = filtered_df = df[
    (df['band_gap'] >= 0.65) & (df['band_gap'] <= 3.0) &
    (df['Octahedral_Factor'] >= 0.44) & (df['Octahedral_Factor'] <= 0.9) &
    (df['Tolerance_Factor'] >= 0.82) & (df['Tolerance_Factor'] <= 1.08) &
    (df['stable'] == 1) & (df['Insulator'] == 1)
]

In [ ]:
stable_semiconductor = stable_conductor[(stable_conductor['PBE_bandgap'] > 1.1) & (stable_conductor['PBE_bandgap'] < 1.6)]

In [ ]:
stable_semiconductor

,A1_OS,B1_OS,A2_OS,B2_OS,X-A1,X-A2,X-B1,X-B2,I-A1,I-A2,...,3DOE-A2,3DOE-B1,3DOE-B2,type_A1A2B1B2O6,type_A1A2B2O6,type_A2B1B2O6,type_ABO3,stable,Insulator,PBE_bandgap
1003,2,2,2,6,1.13,1.13,1.14,1.55,535.5,535.5,...,-37.625433,-35.754515,-0.266540,0.0,0.0,1.0,0.0,1,1,1.296362
1330,3,3,3,3,1.13,1.13,1.36,1.88,535.5,535.5,...,-37.625433,-0.131080,-0.322368,0.0,0.0,1.0,0.0,1,1,1.311123
2312,2,2,2,6,1.13,1.13,1.13,1.55,535.5,535.5,...,-37.625433,-33.913996,-0.266540,0.0,0.0,1.0,0.0,1,1,1.128724
2374,2,5,3,2,1.13,1.13,1.13,1.00,535.5,535.5,...,-37.625433,-33.913996,0.300000,0.0,0.0,1.0,0.0,1,1,1.269209
3229,3,3,3,3,1.13,1.13,1.61,1.88,535.5,535.5,...,-37.625433,1.800000,-0.322368,0.0,0.0,1.0,0.0,1,1,1.246400
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15741247,3,1,2,6,2.20,1.20,0.98,2.36,878.0,592.4,...,-43.754556,2.000000,-66.724787,1.0,0.0,0.0,0.0,1,1,1.307621
15741311,3,1,2,6,2.20,1.20,0.93,2.36,878.0,592.4,...,-43.754556,1.500000,-66.724787,1.0,0.0,0.0,0.0,1,1,1.338352
15805535,3,2,1,6,2.20,0.79,1.25,2.36,878.0,375.7,...,-26.418398,-53.835494,-66.724787,1.0,0.0,0.0,0.0,1,1,1.394364
15808589,3,2,1,6,2.20,0.79,0.95,2.36,878.0,375.7,...,-26.418398,-4.813498,-66.724787,1.0,0.0,0.0,0.0,1,1,1.382173
15852398,3,1,2,6,2.20,1.10,0.98,2.16,878.0,603.4,...,-56.026315,2.000000,-8.257721,1.0,0.0,0.0,0.0,1,1,1.296221