In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
training_data = pd.read_csv('/Users/sohanurrahman/Desktop/research/perovskite/oxide/code/data/raw/training_compounds.csv')
training_data.head()

,A1,A1_OS,A2,A2_OS,B1,B1_OS,B2,B2_OS,Insulator,PBE_band_gap,...,mu_bar,stable,type,data_type,A1_CN,O_cl_eigenenergy,avg_Z,volume,Perovskite,HSE_band_gap
0,Pm,3,Pm,3,Mn,3,Mn,3,0,0.0000,...,0.0,1,ABO3,s,NaN,NaN,NaN,NaN,NaN,NaN
1,Fe,3,Fe,3,Bi,3,Bi,3,0,0.0000,...,0.0,0,ABO3,s,12.0,NaN,NaN,NaN,NaN,NaN
2,Tl,3,Tl,3,Co,3,Co,3,0,0.0000,...,0.0,1,ABO3,s,12.0,NaN,NaN,NaN,NaN,NaN
3,Dy,2,Dy,2,Ir,4,Ir,4,0,0.0000,...,0.0,0,ABO3,s,12.0,NaN,NaN,NaN,NaN,NaN
4,Nd,3,Nd,3,Tl,3,Tl,3,0,0.4159,...,0.0,0,ABO3,s,12.0,NaN,NaN,NaN,NaN,NaN

In [4]:
training_data[training_data['type']=='A1A2B1B2O6' ].head(10)

,A1,A1_OS,A2,A2_OS,B1,B1_OS,B2,B2_OS,Insulator,PBE_band_gap,...,mu_bar,stable,type,data_type,A1_CN,O_cl_eigenenergy,avg_Z,volume,Perovskite,HSE_band_gap
1469,Ba,2,Ba,2,Al,3,Nb,5,1,2.7926,...,0.0,1,A1A2B1B2O6,sp,12.0,-500.7480,21.4,131.613806,1.0,NaN
1470,Ba,2,Ba,2,Bi,3,Ir,5,0,0.0008,...,0.0,1,A1A2B1B2O6,sp,12.0,NaN,NaN,NaN,1.0,NaN
1471,Ba,2,Ba,2,Bi,3,Nb,5,1,2.1098,...,0.0,1,A1A2B1B2O6,sp,12.0,-501.2559,28.4,165.169727,1.0,NaN
1472,Ba,2,Ba,2,Bi,3,Ru,5,0,0.0008,...,0.0,0,A1A2B1B2O6,sp,12.0,NaN,NaN,NaN,0.0,NaN
1473,Ba,2,Ba,2,Ca,2,Mo,6,1,1.9818,...,0.0,1,A1A2B1B2O6,sp,12.0,-501.5387,22.2,153.120118,1.0,NaN
1474,Ba,2,Ba,2,Ca,2,Pu,6,0,0.0000,...,0.0,1,A1A2B1B2O6,sp,12.0,NaN,NaN,NaN,1.0,NaN
1475,Ba,2,Ba,2,Ca,2,Re,6,0,0.0000,...,0.0,1,A1A2B1B2O6,sp,12.0,NaN,NaN,NaN,1.0,NaN
1476,Ba,2,Ba,2,Ca,2,W,6,1,2.7194,...,0.0,1,A1A2B1B2O6,sp,12.0,-501.6168,25.4,153.603331,1.0,NaN
1477,Ba,2,Ba,2,Cd,2,Mo,6,1,2.2380,...,0.0,1,A1A2B1B2O6,sp,12.0,-501.8612,25.0,151.501940,1.0,NaN
1478,Ba,2,Ba,2,Cd,2,Os,6,0,0.0000,...,0.0,1,A1A2B1B2O6,sp,12.0,NaN,NaN,NaN,1.0,NaN

In [28]:
training_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5152 entries, 0 to 5151
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   A1                5152 non-null   object
 1   A1_OS             5152 non-null   int64
 2   A2                5152 non-null   object
 3   A2_OS             5152 non-null   int64
 4   B1                5152 non-null   object
 5   B1_OS             5152 non-null   int64
 6   B2                5152 non-null   object
 7   B2_OS             5152 non-null   int64
 8   Insulator         5152 non-null   int64
 9   PBE_band_gap      5152 non-null   float64
 10  functional_group  5152 non-null   object
 11  mu_bar            5152 non-null   float64
 12  stable            5152 non-null   int64
 13  type              5152 non-null   object
 14  data_type         5152 non-null   object
 15  A1_CN             5151 non-null   float64
 16  O_cl_eigenenergy  943 non-null    float64
 17  avg_Z             943 non-null    float64
 18  volume            943 non-null    float64
 19  Perovskite        1099 non-null   float64
 20  HSE_band_gap      121 non-null    float64
dtypes: float64(8), int64(6), object(7)
memory usage: 845.4+ KB

In [29]:
training_data[['A1', 'A2', 'B1', 'B2']] = training_data[['A1', 'A2', 'B1', 'B2']].astype(str)
display(training_data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5152 entries, 0 to 5151
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   A1                5152 non-null   object
 1   A1_OS             5152 non-null   int64
 2   A2                5152 non-null   object
 3   A2_OS             5152 non-null   int64
 4   B1                5152 non-null   object
 5   B1_OS             5152 non-null   int64
 6   B2                5152 non-null   object
 7   B2_OS             5152 non-null   int64
 8   Insulator         5152 non-null   int64
 9   PBE_band_gap      5152 non-null   float64
 10  functional_group  5152 non-null   object
 11  mu_bar            5152 non-null   float64
 12  stable            5152 non-null   int64
 13  type              5152 non-null   object
 14  data_type         5152 non-null   object
 15  A1_CN             5151 non-null   float64
 16  O_cl_eigenenergy  943 non-null    float64
 17  avg_Z             943 non-null    float64
 18  volume            943 non-null    float64
 19  Perovskite        1099 non-null   float64
 20  HSE_band_gap      121 non-null    float64
dtypes: float64(8), int64(6), object(7)
memory usage: 845.4+ KB

None

In [30]:
Electronegativity = {
    'Pm': 1.13, 'Fe': 1.83, 'Tl': 1.62, 'Dy': 1.22, 'Nd': 1.14, 'Ce': 1.12,
    'Au': 2.54, 'Eu': 1.2, 'Tm': 1.25, 'Pr': 1.13, 'Er': 1.24, 'Lu': 1.27,
    'Cd': 1.69, 'Cr': 1.66, 'Tb': 1.1, 'Mn': 1.55, 'Y': 1.22, 'Sm': 1.17,
    'Hg': 2.0, 'La': 1.1, 'Ho': 1.23, 'Ag': 1.93, 'Sr': 0.95, 'Ca': 1.0,
    'Gd': 1.2, 'Ti': 1.54, 'Co': 1.88, 'In': 1.78, 'Bi': 2.02, 'Zn': 1.65,
    'Tc': 1.9, 'Sc': 1.36, 'K': 0.82, 'Li': 0.98, 'Pd': 2.2, 'Cu': 1.9,
    'Pb': 2.33, 'Ba': 0.89, 'Sb': 2.05, 'Cs': 0.79, 'Mo': 2.16, 'Mg': 1.31,
    'Rb': 0.82, 'Al': 1.61, 'As': 2.18, 'Ga': 1.81, 'Na': 0.93, 'Ni': 1.91,
    'V': 1.63, 'Yb': 1.1, 'Pt': 2.28, 'Hf': 1.3, 'W': 2.36, 'Nb': 1.6, 'Ta': 1.5,
    'Re': 1.9, 'Zr': 1.33, 'Te': 2.1, 'Rh': 2.28, 'Sn': 1.96, 'Ru': 2.2,
    'Ge': 2.01, 'B': 2.04, 'Be': 1.57, 'Os': 2.2, 'Si': 1.9, 'Ir': 2.2, 'I': 2.66,
    'Br': 2.96, 'N': 3.04, 'C': 2.55, 'Pu': 1.28, 'Se': 2.55, 'P': 2.19
}




# ======================================================================
# Ionization energy (kJ/mol) for specified elements
# ======================================================================

IonizationEnergy = {
    'Pm': 535.5, 'Fe': 759.3, 'Tl': 589.3, 'Dy': 572.2, 'Nd': 529.7, 'Ce': 527.8,
    'Au': 890.1, 'Eu': 547.1, 'Tm': 596.3, 'Pr': 523.0, 'Er': 588.6, 'Lu': 523.5,
    'Cd': 867.7, 'Cr': 652.8, 'Tb': 564.4, 'Mn': 717.4, 'Y': 615.6, 'Sm': 543.2,
    'Hg': 1007.1, 'La': 538.1, 'Ho': 580.8, 'Ag': 731.0, 'Sr': 549.5, 'Ca': 589.8,
    'Gd': 592.4, 'Ti': 658.0, 'Co': 758.4, 'In': 558.3, 'Bi': 703.3, 'Zn': 906.4,
    'Tc': 702.0, 'Sc': 631.0, 'K': 418.8, 'Li': 520.2, 'Pd': 890.1, 'Cu': 745.4,
    'Pb': 715.5, 'Ba': 502.9, 'Sb': 833.7, 'Cs': 375.7, 'Mo': 684.9, 'Mg': 737.7,
    'Rb': 403.0, 'Al': 577.6, 'As': 946.5, 'Ga': 578.8, 'Na': 495.8, 'Ni': 736.7,
    'V': 650.3, 'Yb': 603.4, 'Pt': 868.4, 'Hf': 675.4, 'W': 770.0, 'Nb': 663.8,
    'Ta': 761.3, 'Re': 760.3, 'Zr': 660.0, 'Te': 869.2, 'Rh': 868.4, 'Sn': 708.6,
    'Ru': 710.2, 'Ge': 762.1, 'B': 800.6, 'Be': 899.5, 'Os': 840.0, 'Si': 786.5,
    'Ir': 878.0, 'I': 1008.4, 'Br': 1140.0, 'N': 1402.3, 'C': 1086.5, 'Pu': 584.7,
    'Se': 940.9, 'P': 1011.8
}



# ======================================================================
# HOMO energy (eV) for specified elements
# ======================================================================

HOMOEnergy = {
    'Pm': -2.892, 'Fe': -4.434, 'Tl': -2.367, 'Dy': -2.507, 'Nd': -2.98, 'Ce': -2.885,
    'Au': -5.76, 'Eu': -2.735, 'Tm': -2.042, 'Pr': -3.055, 'Er': -2.15, 'Lu': -1.818,
    'Cd': -5.659, 'Cr': -4.417, 'Tb': -2.483, 'Mn': -4.444, 'Y': -2.562, 'Sm': -2.797,
    'Hg': -4.434, 'La': -2.885, 'Ho': -2.261, 'Ag': -4.405, 'Sr': -3.528, 'Ca': -3.768,
    'Gd': -2.168, 'Ti': -4.368, 'Co': -4.436, 'In': -2.516, 'Bi': -4.57, 'Zn': -5.979,
    'Tc': -4.36, 'Sc': -3.29, 'K': -2.33, 'Li': -2.874, 'Pd': -5.1, 'Cu': -3.496,
    'Pb': -3.496, 'Ba': -3.235, 'Sb': -4.827, 'Cs': -2.109, 'Mo': -4.234, 'Mg': -4.706,
    'Rb': -2.246, 'Al': -2.711, 'As': -5.194, 'Ga': -2.577, 'Na': -2.747, 'Ni': -4.458,
    'V': -4.469, 'Yb': -3.029, 'Pt': -5.277, 'Hf': -2.778, 'W': -4.507, 'Nb': -4.617,
    'Ta': -3.652, 'Re': -5.384, 'Zr': -3.668, 'Te': -5.952, 'Rh': -5.277, 'Sn': -3.693,
    'Ru': -4.71, 'Ge': -3.894, 'B': -3.606, 'Be': -4.93, 'Os': -5.11, 'Si': -4.081,
    'Ir': -5.659, 'I': -7.084, 'Br': -11.81, 'N': -14.53, 'C': -11.26, 'Pu': -3.74,
    'Se': -6.51, 'P': -10.49
}


# ======================================================================
# LUMO energy (eV) for specified elements
# ======================================================================

LUMOEnergy = {
    'Pm': -2.794, 'Fe': -4.434, 'Tl': -0.561, 'Dy': -2.247, 'Nd': -2.88, 'Ce': -2.881,
    'Au': -0.556, 'Eu': -1.56, 'Tm': -1.922, 'Pr': -2.957, 'Er': -2.147, 'Lu': -1.698,
    'Cd': -1.181, 'Cr': -4.352, 'Tb': -2.377, 'Mn': -1.061, 'Y': -2.432, 'Sm': -2.698,
    'Hg': -4.1, 'La': -2.881, 'Ho': -2.252, 'Ag': -0.729, 'Sr': -1.287, 'Ca': -1.948,
    'Gd': -1.523, 'Ti': -4.227, 'Co': -0.84, 'In': -0.492, 'Bi': -0.688, 'Zn': -1.113,
    'Tc': -4.08, 'Sc': -3.187, 'K': -0.793, 'Li': -1.09, 'Pd': -5.05, 'Cu': -0.642,
    'Pb': -0.642, 'Ba': -2.026, 'Sb': -0.556, 'Cs': -0.722, 'Mo': -4.079, 'Mg': -1.328,
    'Rb': -0.734, 'Al': -0.444, 'As': -0.532, 'Ga': -0.493, 'Na': -0.732, 'Ni': -0.747,
    'V': -4.362, 'Yb': -1.1, 'Pt': -0.692, 'Hf': -2.774, 'W': -4.408, 'Nb': -4.512,
    'Ta': -3.546, 'Re': -5.355, 'Zr': -3.508, 'Te': -0.56, 'Rh': -0.692, 'Sn': -0.54,
    'Ru': -4.71, 'Ge': -0.529, 'B': -0.298, 'Be': -0.9, 'Os': -5.11, 'Si': -0.462,
    'Ir': -1.181, 'I': -0.556, 'Br': -0.51, 'N': -0.07, 'C': -1.14, 'Pu': -3.1, 'Se': -0.521,
    'P': -0.44
}




# ======================================================================
# Combined Electron Affinity Dictionary (kJ/mol)
# ======================================================================

ElectronAffinity = {
    'Pm': 12.67, 'Fe': 59.6, 'Tl': 41.1, 'Dy': 33.96, 'Nd': 9.4, 'Ce': 15.63,
    'Au': 222.8, 'Eu': 50, 'Tm': 99, 'Pr': 10.539, 'Er': 30.1, 'Lu': 37.043,
    'Cd': 44, 'Cr': 23.04, 'Tb': 12.67, 'Mn': 50, 'Y': 29.6, 'Sm': 15.63,
    'Hg': 37.043, 'La': 50, 'Ho': 32.61, 'Ag': 86.2, 'Sr': 5.023, 'Ca': 2.37,
    'Gd': 48.4, 'Ti': 107.298, 'Co': 30.1, 'In': 18.1, 'Bi': 133.6, 'Zn': 29.6,
    'Tc': 30.88, 'Sc': 44, 'K': -58, 'Li': -50, 'Pd': 195, 'Cu': 18.1,
    'Pb': 32.61, 'Ba': 5.023, 'Sb': 101, 'Cs': 125.7, 'Mo': 50.7, 'Mg': 13.22,
    'Rb': 46.9, 'Al': 31, 'As': 29.6, 'Ga': 31, 'Na': 9.4, 'Ni': 17, 'V': 30,
    'Yb': -40, 'Pt': 30.88, 'Hf': 116, 'W': 78.6, 'Nb': 116, 'Ta': 86.2,
    'Re': 37.043, 'Zr': 12.67, 'Te': 30.1, 'Rh': 23.04, 'Sn': -1.93, 'Ru': 12.67,
    'Ge': 2.37, 'B': 7.6, 'Be': 0, 'Os': 18.1, 'Si': 133.6, 'Ir': 33.96, 'I': 41.1,
    'Br': 30.88, 'N': 29.6, 'C': 1.263, 'Pu': 6.06, 'Se': 15.63, 'P': 23.04
}


# ======================================================================
# Combined Atomic/Z-Radii Dictionary (Å)
# ======================================================================

AtomicZRadii = {
    'Pm': 3.89, 'Fe': 3.6, 'Tl': 3.89, 'Dy': 3.63, 'Nd': 4.14, 'Ce': 3.67,
    'Au': 3.89, 'Eu': 3.37, 'Tm': 3.6, 'Pr': 3.99, 'Er': 3.65, 'Lu': 3.63,
    'Cd': 3.63, 'Cr': 3.67, 'Tb': 3.89, 'Mn': 3.67, 'Y': 3.99, 'Sm': 4.14,
    'Hg': 1.695, 'La': 3.89, 'Ho': 3.65, 'Ag': 3.99, 'Sr': 3.37, 'Ca': 3.08,
    'Gd': 3.67, 'Ti': 3.99, 'Co': 3.37, 'In': 3.65, 'Bi': 3.6, 'Zn': 3.37,
    'Tc': 2.55, 'Sc': 3.65, 'K': 4.48, 'Li': 3.65, 'Pd': 3.37, 'Cu': 3.99,
    'Pb': 3.99, 'Ba': 3.37, 'Sb': 3.37, 'Cs': 3.37, 'Mo': 3.37, 'Mg': 3.63,
    'Rb': 3.37, 'Al': 3.37, 'As': 3.37, 'Ga': 3.37, 'Na': 3.37, 'Ni': 3.37,
    'V': 3.37, 'Yb': 3.37, 'Pt': 3.37, 'Hf': 3.37, 'W': 3.37, 'Nb': 3.37,
    'Ta': 3.37, 'Re': 3.37, 'Zr': 3.37, 'Te': 3.37, 'Rh': 3.37, 'Sn': 3.37,
    'Ru': 3.37, 'Ge': 3.37, 'B': 3.37, 'Be': 0, 'Os': 1.695, 'Si': 3.37,
    'Ir': 3.37, 'I': 3.37, 'Br': 3.68, 'N': 1.32, 'C': 1.32, 'Pu': 3.53, 'Se': 2.26, 'P': 2.07
}




# Thermal Conductivity (W/m·K) for selected elements
element_thermal_conductivity = {
    'Pm':15.0, 'Fe':80.0, 'Tl':46.0, 'Dy':11.0, 'Nd':17.0, 'Ce':11.0, 'Au':320.0, 'Eu':14.0, 'Tm':17.0,
    'Pr':13.0, 'Er':15.0, 'Lu':16.0, 'Cd':97.0, 'Cr':94.0, 'Tb':11.0, 'Mn':7.8, 'Y':17.0, 'Sm':13.0,
    'Hg':8.3, 'La':13.0, 'Ho':16.0, 'Ag':430.0, 'Sr':35.0, 'Ca':200.0, 'Gd':11.0, 'Ti':22.0, 'Co':100.0,
    'In':82.0, 'Bi':8.0, 'Zn':120.0, 'Tc':51.0, 'Sc':16.0, 'K':100.0, 'Li':85.0, 'Pd':72.0, 'Cu':400.0,
    'Pb':35.0, 'Ba':18.0, 'Sb':24.0, 'Cs':36.0, 'Mo':139.0, 'Mg':160.0, 'Rb':58.0, 'Al':235.0, 'As':50.0,
    'Ga':29.0, 'Na':140.0, 'Ni':91.0, 'V':31.0, 'Yb':39.0, 'Pt':72.0, 'Hf':23.0, 'W':170.0, 'Nb':54.0,
    'Ta':57.0, 'Re':48.0, 'Zr':23.0, 'Te':3.0, 'Rh':150.0, 'Sn':67.0, 'Ru':120.0, 'Ge':60.0, 'B':27.0,
    'Be':190.0, 'Os':88.0, 'Si':150.0, 'Ir':150.0, 'I':0.449, 'Br':0.12, 'N':0.0002598, 'C':140.0, 'Pu':6.0,
    'Se':0.52, 'P':0.236
}

# Thermal Expansion (1/K) for selected elements
element_thermal_expansion = {
    'Pm':11e-6, 'Fe':11.8e-6, 'Tl':29.9e-6, 'Dy':9.9e-6, 'Nd':9.6e-6, 'Ce':6.3e-6, 'Au':14.2e-6,
    'Eu':35e-6, 'Tm':13.3e-6, 'Pr':6.7e-6, 'Er':12.2e-6, 'Lu':9.9e-6, 'Cd':30.8e-6, 'Cr':4.9e-6,
    'Tb':10.3e-6, 'Mn':21.7e-6, 'Y':10.6e-6, 'Sm':12.7e-6, 'Hg':1.8e-8, 'La':12.1e-6, 'Ho':11.2e-6,
    'Ag':18.9e-6, 'Sr':22.5e-6, 'Ca':22.3e-6, 'Gd':9.4e-6, 'Ti':8.6e-6, 'Co':13.0e-6, 'In':32.1e-6,
    'Bi':13.4e-6, 'Zn':30.2e-6, 'Tc':6.4e-6, 'Sc':10.2e-6, 'K':83.3e-6, 'Li':46e-6, 'Pd':11.8e-6,
    'Cu':16.5e-6, 'Pb':28.9e-6, 'Ba':20.6e-6, 'Sb':11e-6, 'Cs':6.3e-6, 'Mo':4.8e-6, 'Mg':8.2e-6,
    'Rb':9e-6, 'Al':23.1e-6, 'As':4.7e-6, 'Ga':120e-6, 'Na':71e-6, 'Ni':13.4e-6, 'V':8.4e-6, 'Yb':26.3e-6,
    'Pt':8.8e-6, 'Hf':5.9e-6, 'W':4.5e-6, 'Nb':7.3e-6, 'Ta':6.3e-6, 'Re':6.2e-6, 'Zr':5.7e-6, 'Te':17.9e-6,
    'Rh':8.2e-6, 'Sn':22e-6, 'Ru':6.4e-6, 'Ge':6.0e-6, 'B':6e-6, 'Be':11.3e-6, 'Os':5.1e-6, 'Si':2.6e-6,
    'Ir':6.4e-6, 'I':0.04e-6, 'Br':6.4e-6, 'N': 0.01e-6, 'C':7.1e-6, 'Pu':1.5e-7, 'Se':37e-6, 'P':5.0e-7
}


# Atom formation enthalpy (Kj/mol)

atom_formation_enthalpy = {
    'Pm': 0, 'Fe': 418, 'Tl': 182, 'Dy': 297, 'Nd': 322, 'Ce': 422, 'Au': 366,
    'Eu': 176, 'Tm': 230, 'Pr': 355, 'Er': 318, 'Lu': 426, 'Cd': 112, 'Cr': 397,
    'Tb': 389, 'Mn': 281, 'Y': 423, 'Sm': 205, 'Hg': 61.5, 'La': 423, 'Ho': 301,
    'Ag': 284, 'Sr': 164, 'Ca': 178, 'Gd': 397, 'Ti': 470, 'Co': 425, 'In': 243,
    'Bi': 207, 'Zn': 131, 'Tc': 51, 'Sc': 378, 'K': 90, 'Li': 161, 'Pd': 72,
    'Cu': 338, 'Pb': 196, 'Ba': 180, 'Sb': 262, 'Cs': 79, 'Mo': 658, 'Mg': 148,
    'Rb': 86, 'Al': 326, 'As': 302, 'Ga': 286, 'Na': 109, 'Ni': 430, 'V': 514,
    'Yb': 150, 'Pt': 565, 'Hf': 619, 'W': 849, 'Nb': 726, 'Ta': 782, 'Re': 770,
    'Zr': 609, 'Te': 197, 'Rh': 556, 'Sn': 302, 'Ru': 120, 'Ge': 377, 'B': 573,
    'Be': 190, 'Os': 88, 'Si': 452, 'Ir': 665, 'I': 107, 'Br': 0.12, 'N': 0,
    'C': 0, 'Pu': 348, 'Se': 227, 'P': 236
}

elements_3d_orbital_energy = {
    'Pm': -37.625433, 'Fe': -0.295049, 'Tl': -88.328299, 'Dy': -47.4867,
    'Nd': -35.754515, 'Ce': -32.412569, 'Au': -81.511751, 'Eu': -41.465518,
    'Tm': -53.835494, 'Pr': -33.913996, 'Er': -51.682149, 'Lu': -58.592982,
    'Cd': -14.685252, 'Cr': -0.118123, 'Tb': -45.443863, 'Mn': -0.26654,
    'Y': -5.671499, 'Sm': -39.528656, 'Hg': -84.845492, 'La': -30.626696,
    'Ho': -49.565996, 'Ag': -13.367803, 'Sr': -4.813498, 'Ca': 0.3,
    'Gd': -43.754556, 'Ti': -0.17001, 'Co': -0.322368, 'In': -16.139823,
    'Bi': -95.532476, 'Zn': -0.398944, 'Tc': -9.33986, 'Sc': -0.13108,
    'K': 1, 'Li': 2, 'Pd': -12.132197, 'Cu': -0.202272, 'Pb': -91.889924,
    'Ba': -28.528933, 'Sb': -19.239895, 'Cs': -26.418398, 'Mo': -8.257721,
    'Mg': 2, 'Rb': -3.915508, 'Al': 1.8, 'As': -1.542767, 'Ga': -0.736204,
    'Na': 1.5, 'Ni': -0.348699, 'V': -0.204634, 'Yb': -56.026315,
    'Pt': -78.400271, 'Hf': -61.231443, 'W': -66.724787, 'Nb': -7.339839,
    'Ta': -63.942521, 'Re': -69.57676, 'Zr': -6.544643, 'Te': -20.887801,
    'Rh': -11.21725, 'Sn': -17.657276, 'Ru': -10.195668, 'Ge': -1.117316,
    'B': 2.5, 'Be': 1.9, 'Os': -72.497183, 'Si': 1.8, 'Ir': -75.485027,
    'I': -22.600693, 'Br': -2.52211, 'N': 2.5, 'C': 140.0, 'Pu': -3778,
    'Se': -2.011392, 'P': 0.236
}


ionic_radius_pm = {
    'Pm': 97.9, 'Fe': 64.5, 'Tl': 88.5, 'Dy': 91.2, 'Nd': 98.3, 'Ce': 87,
    'Au': 85, 'Eu': 94.7, 'Tm': 88.0, 'Pr': 99, 'Er': 89.0, 'Lu': 86.1,
    'Cd': 95, 'Cr': 61.5, 'Tb': 92.3, 'Mn': 83, 'Y': 90.0, 'Sm': 95.8,
    'Hg': 102, 'La': 103.2, 'Ho': 90.1, 'Ag': 115, 'Sr': 118, 'Ca': 100,
    'Gd': 93.8, 'Ti': 60.5, 'Co': 74.5, 'In': 80, 'Bi': 103, 'Zn': 74,
    'Tc': 64.5, 'Sc': 74.5, 'K': 138, 'Li': 76, 'Pd': 86, 'Cu': 73,
    'Pb': 119, 'Ba': 135, 'Sb': 76, 'Cs': 167, 'Mo': 59, 'Mg': 72,
    'Rb': 152, 'Al': 53.5, 'As': 58, 'Ga': 62, 'Na': 102, 'Ni': 69,
    'V': 54, 'Yb': 86.8, 'Pt': 62.5, 'Hf': 71, 'W': 60, 'Nb': 64,
    'Ta': 64, 'Re': 53, 'Zr': 72, 'Te': 97, 'Rh': 66.5, 'Sn': 69,
    'Ru': 62, 'Ge': 53, 'B': 27, 'Be': 45, 'Os': 63, 'Si': 40,
    'Ir': 62.5, 'I': 95, 'Br': 59, 'N': 13, 'C': 16, 'Pu': 86,
    'Se': 69, 'P': 38
}

bond_energy_with_oxygen = {
    'Pm': 674,
    'Fe': 409,
    'Tl': 445.2,     # no Tl–O in that reference table
    'Dy': 611,
    'Nd': 703,
    'Ce': 795,
    'Au': 290,     # Au–O is not in that table
    'Eu': 557,
    'Tm': 557,
    'Pr': 753,
    'Er': 611,
    'Lu': 695,
    'Cd': 142,
    'Cr': 477,     # Cr–O not listed
    'Tb': 707,
    'Mn': 402,
    'Y': 715.1,
    'Sm': 619,
    'Hg': 330,     # Hg–O not listed
    'La': 799,
    'Ho': 437,     # Ho–O not listed
    'Ag': 213,
    'Sr': 454,
    'Ca': 464,
    'Gd': 716,
    'Ti': 662,
    'Co': 368,
    'In': 360,
    'Bi': 343,
    'Zn': 284.1,
    'Tc': 435,     # Tc–O not listed
    'Sc': 674,
    'K': 239,
    'Li': 341,
    'Pd': 234,      # Pd–O = 234
    'Cu': 343,
    'Pb': 378,
    'Ba': 482,     # Ba–O not listed
    'Sb': 473,     # Sb–O not listed
    'Cs': 297,
    'Mo': 607,
    'Mg': 394,
    'Rb': 255,
    'Al': 512,     # Al–O not in that reference table, though known elsewhere (~512)
    'As': 481,     # As–O not listed
    'Ga': 285,
    'Na': 257,
    'Ni': 391.6,
    'V': 644,
    'Yb': 397.9,
    'Pt': 347,     # Pt–O not listed (but reference has Pt–O = 347)
    'Hf': 791,
    'W': 653,
    'Nb': 753,
    'Ta': 805,
    'Re': 466,     # Re–O not in that reference table
    'Zr': 760,
    'Te': 391,
    'Rh': 377,
    'Sn': 548,
    'Ru': 481,
    'Ge': 662,
    'B': 806,
    'Be': 448,
    'Os': 301,
    'Si': 798,
    'Ir': 352,
    'I': 184,
    'Br': 235.1,
    'N': 630.57,
    'C': 798,         # for C–O the table uses “Si9O = 798” but that is Si–O; for carbon, many C–O values vary, but using Si9O as guide is not perfect
    'Pu': 473,       # Pu–O not listed
    'Se': 423,
    'P': 596.6
}
atomic_polarizability = {
    'Pm': 200,
    'Fe': 3.15,
    'Tl': 11.2,
    'Dy': 163,
    'Nd': 208,
    'Ce': 205,
    'Au': 12.0,
    'Eu': 184,
    'Tm': 144,
    'Pr': 216,
    'Er': 150,
    'Lu': 137,
    'Cd': 9.5,
    'Cr': 3.0,
    'Tb': 170,
    'Mn': 68,
    'Y': 162,
    'Sm': 192,
    'Hg': 11.0,
    'La': 215,
    'Ho': 156,
    'Ag': 8.0,
    'Sr': 197.2,
    'Ca': 160.8,
    'Gd': 158,
    'Ti': 100,
    'Co': 55,
    'In': 65,
    'Bi': 48,
    'Zn': 5.0,
    'Tc': 79,
    'Sc': 97,
    'K': 2.0,
    'Li': 1.0,
    'Pd': 8.0,
    'Cu': 5.0,
    'Pb': 47,
    'Ba': 272,
    'Sb': 43,
    'Cs': 400.9,
    'Mo': 87,
    'Mg': 71.2,
    'Rb': 319.8,
    'Al': 2.0,
    'As': 30.1,
    'Ga': 50,
    'Na': 1.5,
    'Ni': 49,
    'V': 87,
    'Yb': 139,
    'Pt': 48,
    'Hf': 103,
    'W': 68,
    'Nb': 98,
    'Ta': 74,
    'Re': 62,
    'Zr': 112,
    'Te': 38,
    'Rh': 66,
    'Sn': 53,
    'Ru': 72,
    'Ge': 40,
    'B': 20.5,
    'Be': 37.74,
    'Os': 57,
    'Si': 37.3,
    'Ir': 54,
    'I': 32.9,
    'Br': 21,
    'N': 7.4,
    'C': 7.4,
    'Pu': 132,
    'Se': 28.9,
    'P': 25
}

In [31]:
training_data.columns

Index(['A1', 'A1_OS', 'A2', 'A2_OS', 'B1', 'B1_OS', 'B2', 'B2_OS', 'Insulator',
       'PBE_band_gap', 'functional_group', 'mu_bar', 'stable', 'type',
       'data_type', 'A1_CN', 'O_cl_eigenenergy', 'avg_Z', 'volume',
       'Perovskite', 'HSE_band_gap'],
      dtype='object')

In [32]:
df = training_data.drop(columns=['O_cl_eigenenergy', 'avg_Z', 'volume',
       'Perovskite', 'HSE_band_gap'])

In [33]:
df['X-A1'] = df['A1'].map(Electronegativity)
df['X-A2'] = df['A2'].map(Electronegativity)
df['X-B1'] = df['B1'].map(Electronegativity)
df["X-B2"] = df['B2'].map(Electronegativity)

In [34]:
df['I-A1'] = df['A1'].map(IonizationEnergy)
df['I-A2'] = df['A2'].map(IonizationEnergy)
df['I-B1'] = df['B1'].map(IonizationEnergy)
df["I-B2"] = df['B2'].map(IonizationEnergy)

In [35]:
df['P-A1'] = df['A1'].map(atomic_polarizability)
df['P-A2'] = df['A2'].map(atomic_polarizability)
df['P-B1'] = df['B1'].map(atomic_polarizability)
df["P-B2"] = df['B2'].map(atomic_polarizability)

In [36]:
df["R-A1"] = df['A1'].map(ionic_radius_pm)
df["R-A2"] = df['A2'].map(ionic_radius_pm)
df["R-B1"] = df['B1'].map(ionic_radius_pm)
df["R-B2"] = df['B2'].map(ionic_radius_pm)

In [37]:
df['RA-A1'] = df['A1'].map(AtomicZRadii)
df['RA-A2'] = df['A2'].map(AtomicZRadii)
df['RA-B1'] = df['B1'].map(AtomicZRadii)
df["RA-B2"] = df['B2'].map(AtomicZRadii)

In [38]:
df['H-A1'] = df['A1'].map(HOMOEnergy)
df['H-A2'] = df['A2'].map(HOMOEnergy)
df['H-B1'] = df['B1'].map(HOMOEnergy)
df["H-B2"] = df['B2'].map(HOMOEnergy)

In [39]:
df["L-A1"] = df['A1'].map(LUMOEnergy)
df["L-A2"] = df['A2'].map(LUMOEnergy)
df["L-B1"] = df['B1'].map(LUMOEnergy)
df["L-B2"] = df['B2'].map(LUMOEnergy)

In [40]:
df["EA-A1"] = df['A1'].map(ElectronAffinity)
df["EA-A2"] = df['A2'].map(ElectronAffinity)
df["EA-B1"] = df['B1'].map(ElectronAffinity)
df["EA-B2"] = df['B2'].map(ElectronAffinity)

In [41]:
df["TC-A1"] = df['A1'].map(element_thermal_conductivity)
df["TC-A2"] = df['A2'].map(element_thermal_conductivity)
df["TC-B1"] = df['B1'].map(element_thermal_conductivity)
df["TC-B2"] = df['B2'].map(element_thermal_conductivity)

In [42]:
df['TE-A1'] = df['A1'].map(element_thermal_expansion)
df['TE-A2'] = df['A2'].map(element_thermal_expansion)
df['TE-B1'] = df['B1'].map(element_thermal_expansion)
df['TE-B2'] = df['B2'].map(element_thermal_expansion)

In [43]:
df['EH-A1'] = df['A1'].map(atom_formation_enthalpy)
df['EH-A2'] = df['A2'].map(atom_formation_enthalpy)
df['EH-B1'] = df['B1'].map(atom_formation_enthalpy)
df['EH-B2'] = df['B2'].map(atom_formation_enthalpy)

In [44]:
df['BE-A1'] = df['A1'].map(bond_energy_with_oxygen)
df['BE-A2'] = df['A2'].map(bond_energy_with_oxygen)
df['BE-B1'] = df['B1'].map(bond_energy_with_oxygen)
df['BE-B2'] = df['B2'].map(bond_energy_with_oxygen)

In [45]:
df['3DOE-A1'] = df['A1'].map(elements_3d_orbital_energy)
df['3DOE-A2'] = df['A2'].map(elements_3d_orbital_energy)
df['3DOE-B1'] = df['B1'].map(elements_3d_orbital_energy)
df['3DOE-B2'] = df['B2'].map(elements_3d_orbital_energy)

In [46]:
df.columns

Index(['A1', 'A1_OS', 'A2', 'A2_OS', 'B1', 'B1_OS', 'B2', 'B2_OS', 'Insulator',
       'PBE_band_gap', 'functional_group', 'mu_bar', 'stable', 'type',
       'data_type', 'A1_CN', 'X-A1', 'X-A2', 'X-B1', 'X-B2', 'I-A1', 'I-A2',
       'I-B1', 'I-B2', 'P-A1', 'P-A2', 'P-B1', 'P-B2', 'R-A1', 'R-A2', 'R-B1',
       'R-B2', 'RA-A1', 'RA-A2', 'RA-B1', 'RA-B2', 'H-A1', 'H-A2', 'H-B1',
       'H-B2', 'L-A1', 'L-A2', 'L-B1', 'L-B2', 'EA-A1', 'EA-A2', 'EA-B1',
       'EA-B2', 'TC-A1', 'TC-A2', 'TC-B1', 'TC-B2', 'TE-A1', 'TE-A2', 'TE-B1',
       'TE-B2', 'EH-A1', 'EH-A2', 'EH-B1', 'EH-B2', 'BE-A1', 'BE-A2', 'BE-B1',
       'BE-B2', '3DOE-A1', '3DOE-A2', '3DOE-B1', '3DOE-B2'],
      dtype='object')

In [ ]:
from sklearn.preprocessing import  OneHotEncoder

onehot_encoder = OneHotEncoder(sparse_output=False)
type_encoded = onehot_encoder.fit_transform(df[['type']])
type_encoded_df = pd.DataFrame(type_encoded, columns=onehot_encoder.get_feature_names_out(['type']))

df = pd.concat([df, type_encoded_df], axis=1)

df = df.drop(columns=['data_type', 'type','A1', 'A2', 'B1', 'B2','functional_group','A1_CN','mu_bar'])

display(df.head())

,A1_OS,A2_OS,B1_OS,B2_OS,Insulator,PBE_band_gap,stable,X-A1,X-A2,X-B1,...,BE-B1,BE-B2,3DOE-A1,3DOE-A2,3DOE-B1,3DOE-B2,type_A1A2B1B2O6,type_A1A2B2O6,type_A2B1B2O6,type_ABO3
0,3,3,3,3,0,0.0000,1,1.13,1.13,1.55,...,402.0,402.0,-37.625433,-37.625433,-0.266540,-0.266540,0.0,0.0,0.0,1.0
1,3,3,3,3,0,0.0000,0,1.83,1.83,2.02,...,343.0,343.0,-0.295049,-0.295049,-95.532476,-95.532476,0.0,0.0,0.0,1.0
2,3,3,3,3,0,0.0000,1,1.62,1.62,1.88,...,368.0,368.0,-88.328299,-88.328299,-0.322368,-0.322368,0.0,0.0,0.0,1.0
3,2,2,4,4,0,0.0000,0,1.22,1.22,2.20,...,352.0,352.0,-47.486700,-47.486700,-75.485027,-75.485027,0.0,0.0,0.0,1.0
4,3,3,3,3,0,0.4159,0,1.14,1.14,1.62,...,445.2,445.2,-35.754515,-35.754515,-88.328299,-88.328299,0.0,0.0,0.0,1.0

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5152 entries, 0 to 5151
Data columns (total 63 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   A1_OS            5152 non-null   int64
 1   A2_OS            5152 non-null   int64
 2   B1_OS            5152 non-null   int64
 3   B2_OS            5152 non-null   int64
 4   Insulator        5152 non-null   int64
 5   PBE_band_gap     5152 non-null   float64
 6   stable           5152 non-null   int64
 7   X-A1             5152 non-null   float64
 8   X-A2             5152 non-null   float64
 9   X-B1             5152 non-null   float64
 10  X-B2             5152 non-null   float64
 11  I-A1             5152 non-null   float64
 12  I-A2             5152 non-null   float64
 13  I-B1             5152 non-null   float64
 14  I-B2             5152 non-null   float64
 15  P-A1             5152 non-null   float64
 16  P-A2             5152 non-null   float64
 17  P-B1             5152 non-null   float64
 18  P-B2             5152 non-null   float64
 19  R-A1             5152 non-null   float64
 20  R-A2             5152 non-null   float64
 21  R-B1             5152 non-null   float64
 22  R-B2             5152 non-null   float64
 23  RA-A1            5152 non-null   float64
 24  RA-A2            5152 non-null   float64
 25  RA-B1            5152 non-null   float64
 26  RA-B2            5152 non-null   float64
 27  H-A1             5152 non-null   float64
 28  H-A2             5152 non-null   float64
 29  H-B1             5152 non-null   float64
 30  H-B2             5152 non-null   float64
 31  L-A1             5152 non-null   float64
 32  L-A2             5152 non-null   float64
 33  L-B1             5152 non-null   float64
 34  L-B2             5152 non-null   float64
 35  EA-A1            5152 non-null   float64
 36  EA-A2            5152 non-null   float64
 37  EA-B1            5152 non-null   float64
 38  EA-B2            5152 non-null   float64
 39  TC-A1            5152 non-null   float64
 40  TC-A2            5152 non-null   float64
 41  TC-B1            5152 non-null   float64
 42  TC-B2            5152 non-null   float64
 43  TE-A1            5152 non-null   float64
 44  TE-A2            5152 non-null   float64
 45  TE-B1            5152 non-null   float64
 46  TE-B2            5152 non-null   float64
 47  EH-A1            5152 non-null   float64
 48  EH-A2            5152 non-null   float64
 49  EH-B1            5152 non-null   float64
 50  EH-B2            5152 non-null   float64
 51  BE-A1            5152 non-null   float64
 52  BE-A2            5152 non-null   float64
 53  BE-B1            5152 non-null   float64
 54  BE-B2            5152 non-null   float64
 55  3DOE-A1          5152 non-null   float64
 56  3DOE-A2          5152 non-null   float64
 57  3DOE-B1          5152 non-null   float64
 58  3DOE-B2          5152 non-null   float64
 59  type_A1A2B1B2O6  5152 non-null   float64
 60  type_A1A2B2O6    5152 non-null   float64
 61  type_A2B1B2O6    5152 non-null   float64
 62  type_ABO3        5152 non-null   float64
dtypes: float64(57), int64(6)
memory usage: 2.5 MB

In [49]:
df.columns

Index(['A1_OS', 'A2_OS', 'B1_OS', 'B2_OS', 'Insulator', 'PBE_band_gap',
       'stable', 'X-A1', 'X-A2', 'X-B1', 'X-B2', 'I-A1', 'I-A2', 'I-B1',
       'I-B2', 'P-A1', 'P-A2', 'P-B1', 'P-B2', 'R-A1', 'R-A2', 'R-B1', 'R-B2',
       'RA-A1', 'RA-A2', 'RA-B1', 'RA-B2', 'H-A1', 'H-A2', 'H-B1', 'H-B2',
       'L-A1', 'L-A2', 'L-B1', 'L-B2', 'EA-A1', 'EA-A2', 'EA-B1', 'EA-B2',
       'TC-A1', 'TC-A2', 'TC-B1', 'TC-B2', 'TE-A1', 'TE-A2', 'TE-B1', 'TE-B2',
       'EH-A1', 'EH-A2', 'EH-B1', 'EH-B2', 'BE-A1', 'BE-A2', 'BE-B1', 'BE-B2',
       '3DOE-A1', '3DOE-A2', '3DOE-B1', '3DOE-B2', 'type_A1A2B1B2O6',
       'type_A1A2B2O6', 'type_A2B1B2O6', 'type_ABO3'],
      dtype='object')

In [50]:
df.to_csv('../data/processed/training.csv', index=False)